// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ClientApi.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Booking
    {
        /// <summary>
        /// Initializes a new instance of the Booking class.
        /// </summary>
        public Booking()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Booking class.
        /// </summary>
        public Booking(int? id = default(int?), System.DateTime? startDate = default(System.DateTime?), System.DateTime? endDate = default(System.DateTime?), int? userId = default(int?), User user = default(User), Room room = default(Room), int? roomId = default(int?), System.DateTime? modified = default(System.DateTime?), System.DateTime? created = default(System.DateTime?))
        {
            Id = id;
            StartDate = startDate;
            EndDate = endDate;
            UserId = userId;
            User = user;
            Room = room;
            RoomId = roomId;
            Modified = modified;
            Created = created;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "startDate")]
        public System.DateTime? StartDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "endDate")]
        public System.DateTime? EndDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "userId")]
        public int? UserId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "user")]
        public User User { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "room")]
        public Room Room { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "roomId")]
        public int? RoomId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "modified")]
        public System.DateTime? Modified { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "created")]
        public System.DateTime? Created { get; set; }

    }
}
