// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ClientApi.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Hotel
    {
        /// <summary>
        /// Initializes a new instance of the Hotel class.
        /// </summary>
        public Hotel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Hotel class.
        /// </summary>
        public Hotel(int? id = default(int?), string hotelName = default(string), System.DateTime? foundationYear = default(System.DateTime?), string adress = default(string), bool? isActive = default(bool?), IList<Room> rooms = default(IList<Room>), System.DateTime? modified = default(System.DateTime?), System.DateTime? created = default(System.DateTime?))
        {
            Id = id;
            HotelName = hotelName;
            FoundationYear = foundationYear;
            Adress = adress;
            IsActive = isActive;
            Rooms = rooms;
            Modified = modified;
            Created = created;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "hotelName")]
        public string HotelName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "foundationYear")]
        public System.DateTime? FoundationYear { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "adress")]
        public string Adress { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isActive")]
        public bool? IsActive { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "rooms")]
        public IList<Room> Rooms { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "modified")]
        public System.DateTime? Modified { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "created")]
        public System.DateTime? Created { get; set; }

    }
}
