// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ClientApi.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class RoomBookings
    {
        /// <summary>
        /// Initializes a new instance of the RoomBookings class.
        /// </summary>
        public RoomBookings()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the RoomBookings class.
        /// </summary>
        public RoomBookings(int? roomNumber = default(int?), int? countBookings = default(int?), string hotelName = default(string))
        {
            RoomNumber = roomNumber;
            CountBookings = countBookings;
            HotelName = hotelName;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "roomNumber")]
        public int? RoomNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "countBookings")]
        public int? CountBookings { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "hotelName")]
        public string HotelName { get; set; }

    }
}
