// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ClientApi.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Room
    {
        /// <summary>
        /// Initializes a new instance of the Room class.
        /// </summary>
        public Room()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Room class.
        /// </summary>
        public Room(int? id = default(int?), double? price = default(double?), int? number = default(int?), int? capability = default(int?), int? comfortLevel = default(int?), int? hotelId = default(int?), Hotel hotel = default(Hotel), IList<Booking> bookings = default(IList<Booking>), System.DateTime? modified = default(System.DateTime?), System.DateTime? created = default(System.DateTime?))
        {
            Id = id;
            Price = price;
            Number = number;
            Capability = capability;
            ComfortLevel = comfortLevel;
            HotelId = hotelId;
            Hotel = hotel;
            Bookings = bookings;
            Modified = modified;
            Created = created;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "price")]
        public double? Price { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "number")]
        public int? Number { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "capability")]
        public int? Capability { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "comfortLevel")]
        public int? ComfortLevel { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "hotelId")]
        public int? HotelId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "hotel")]
        public Hotel Hotel { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "bookings")]
        public IList<Booking> Bookings { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "modified")]
        public System.DateTime? Modified { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "created")]
        public System.DateTime? Created { get; set; }

    }
}
